# Generated by Django 2.1.4 on 2019-01-02 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.PositiveIntegerField()),
                ('tipo', models.CharField(blank=True, choices=[('p', 'Particular'), ('e', 'Empresa')], default='p', help_text='Tipo de cliente', max_length=1)),
                ('descripcion', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('ci_nro', models.CharField(max_length=20)),
                ('ruc', models.CharField(max_length=20)),
                ('nro_telefonico', models.CharField(max_length=20)),
                ('contacto', models.CharField(max_length=200)),
                ('nro_celular', models.CharField(max_length=20)),
                ('latitud', models.CharField(max_length=20)),
                ('longitud', models.CharField(max_length=20)),
                ('referencias', models.CharField(max_length=200)),
                ('obs', models.CharField(max_length=200)),
                ('nro_sensores', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='estaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion_id', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('latitud', models.CharField(max_length=20)),
                ('longitud', models.CharField(max_length=20)),
                ('nro_telefonico', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='sensores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=1)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servidor.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('puesto', models.CharField(choices=[('Sp', 'Supervisor'), ('En', 'Encargado de turno')], max_length=15)),
                ('estacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servidor.estaciones')),
            ],
        ),
        migrations.AddField(
            model_name='sensores',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servidor.tipo_sensor'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='estacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servidor.estaciones'),
        ),
    ]
