# Generated by Django 2.1.4 on 2019-01-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estaciones',
            name='ciudad',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
