# Generated by Django 2.0.7 on 2019-02-26 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0002_estaciones_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='alarmas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servidor.sensores')),
            ],
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='cliente_id',
        ),
        migrations.RemoveField(
            model_name='estaciones',
            name='estacion_id',
        ),
    ]
