# Generated by Django 2.1.4 on 2019-02-27 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0003_auto_20190226_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmas',
            name='idsensor',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
