# Generated by Django 2.1.4 on 2019-02-27 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0004_alarmas_idsensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensores',
            name='sensor_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
