# Generated by Django 2.1.4 on 2019-03-01 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0006_clientes_id_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmas',
            name='sensor',
        ),
        migrations.AddField(
            model_name='clientes',
            name='estado',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='sensor_act',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='alarmas',
        ),
    ]
